remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 

gem "github-pages", group: :jekyll_plugins

title: Διαχείριση Αποβλήτων
description: Τμήμα Ψηφιακών Συστημάτων, Πανεπιστήμιο Θεσσαλίας

