remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme

gem "github-pages", group: :jekyll_plugins

title: Recycling, Department of Digital Systems, University of Thessaly
#description: Ανακύκλωση 
