remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme

title: Ανακύκλωση, Πανεπιστήμιο Θεσσαλίας, Τμήμα Ψηφιακών Συστημάτων
#description: Ανακύκλωση 

footer_text: >
  Αυτή η σελίδα φτιάχτηκε στα πλαίσια του μαθήματος "Οικολογία και Αειφορία" από τη φοιτήτρια Σοφία Στουπά.
  Καλλιτεχνική συνεισφορά στο project από Άννελι Σοφία Γκαμούλου.

#repo color theme
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy

footer_fixed: true
lang: gr
icon: ♻️

# OPTIONAL for project sites:
# If your Pages site is served at https://onoufrios.github.io/ds_recycling
# uncomment and set these so links are generated correctly:
# baseurl: "/ds_recycling"
# url: "https://onoufrios.github.io"
