remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 

gem "github-pages", group: :jekyll_plugins

title: Ανακύκλωση, Πανεπιστήμιο Θεσσαλίας, Τμήμα Ψηφιακών Συστημάτων
#description: Ανακύκλωση 

#footer_text: >
  #Αυτή η σελίδα φτιάχτηκε στα πλαίσια του μαθήματος "Οικολογία και Αειφορία" από τη φοιτήτρια Σοφία Στουπά.
  #Καλλιτεχνική συνεισφορά στο project από Άννελι Σοφία Γκαμούλου.

#footer_fixed: true
#lang: gr
#icon: ♻️
